kind: Service
apiVersion: v1
metadata:
  name: telegrambot
  labels:
    app: telegrambot
spec:
  selector:
    app: telegrambot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 2345
  type: NodePort
